# TODO: implement translation calls & caching later
# signatures we will use:
# async def translate_text(text: str, target_lang: str, source_lang: str = "en") -> str: ...
# async def translate_block_dict(block: dict[str, str], target_lang: str) -> dict[str, str]: ...
